### ISSUE TITLE
JPA 데이터 호출 시 시계열 타입 직렬화 관련 

### ISSUE THREAD

**Issue by luvris2** [DevBabys/1st-shoppingmall-backend#11]
데이터베이스에 시계열 타입의 컬럼의 값을 JPA로 호출하여 API에 태워 보내줄 때 응답 값이 이상하게 출력됩니다.

**실제 데이터 베이스의 값**
createdAt : 2024-06-14 13:47:24.103970
**API 응답 결과**
{
        "createdAt": [
            2024,
            6,
            14,
            13,
            47,
            24,
            103970000
        ]
}

Jackson을 이용한 방법이 있던데 Jackson Object Mapper를 이용하면 자체적으로 JSON 형식으로 변환해서 쓸데없는 문자열이 붙어요. 응답 결과가 다음과 같이 됩니다.
**"createdAt": "\\"2024-06-14T13:47:24.10397\\""**
혹시 이것 말고 시계열 타입 문자열 포맷팅 관련 처리 경험 있으실까요?
replace로 그냥 빼줘야 하나... ;ㅅ;

**Comment by yek-j** [comment]
데이터 전달 시 DTO를 사용하시나요?

**Comment by luvris2** [comment]
시계열 타입이 있는 서비스가 입력값은 DTO를 사용하는 게 있고 사용하지 않는 것도 있습니다.
반환값은 JSON 형태로 가공해서 반환하고 DTO Response를 따로 두고 있지는 않습니다.

**Comment by luvris2** [comment]
시간 관계상 Jackson Object Mapper를 사용하여 replace하는 방안으로 함.
`objectMapper.writeValueAsString(product.createdAt).replace("\"", "")`
